- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/DeadPackets/pwnbox-cli
    - url: https://github.com/DeadPackets/AUSCrawl

- name: NodeJS
  logo: nodedotjs
  url: https://nodejs.org/
  color: '#339933'
  projects:
    - url: https://github.com/DeadPackets/CRNotify
    - url: https://github.com/DeadPackets/AUSCrawl

- name: Puppeteer
  logo: puppeteer
  url: https://github.com/DeadPackets/DOSArchive
  color: '#40B5A4'
  projects:
    - url: https://github.com/DeadPackets/CRNotify
    - url: https://github.com/DeadPackets/AUSCrawl

- name: Docker
  logo: docker
  url: https://www.docker.com
  color: '#2496ED'
  projects:
    - url: https://github.com/DeadPackets/pwnbox

- name: JavaScript
  logo: javascript
  url: https://www.javascript.com
  color: '#F7DF1E'
  projects:
    - url: https://github.com/DeadPackets/DOSArchive
    - url: https://github.com/DeadPackets/CrackTheHack
    - url: https://github.com/DeadPackets/EmailCheck
    - url: https://github.com/DeadPackets/HistoryThief
