- name: Agentic AI / LLMs
  logo: openai
  url: https://openrouter.ai/
  color: '#412991'
  projects:
    - url: https://github.com/DeadPackets/LLMChessArena
    - url: https://github.com/DeadPackets/PiCodeReview
    - url: https://github.com/DeadPackets/LLMCompanionCord

- name: TypeScript
  logo: typescript
  url: https://www.typescriptlang.org/
  color: '#3178C6'
  projects:
    - url: https://github.com/DeadPackets/LLMChessArena
    - url: https://github.com/DeadPackets/PiCodeReview

- name: Python
  logo: python
  url: https://www.python.org/
  color: '#3C78A9'
  projects:
    - url: https://github.com/DeadPackets/LLMCompanionCord
    - url: https://github.com/DeadPackets/pwnbox-cli

- name: Docker
  logo: docker
  url: https://www.docker.com
  color: '#2496ED'
  projects:
    - url: https://github.com/DeadPackets/pwnbox

- name: Offensive Security
  logo: hackthebox
  url: https://github.com/DeadPackets/RedCrucible
  color: '#9FEF00'
  projects:
    - url: https://github.com/DeadPackets/RedCrucible
    - url: https://github.com/DeadPackets/HackPi
