name: Update Todoist stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  update-todist-stats:
    name: Update Todoist stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: abhisheknaiidu/todoist-readme@master
        with:
          TODOIST_API_KEY: ${{ secrets.TODOIST_API_KEY }}
          PREMIUM: ""