name: Update project spotlight

on:
  workflow_dispatch:

jobs:
  update-project-spotlight:
    name: Update project spotlight
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Matt-Gleich/profile_stack@master
